/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/albums': RouteRecordInfo<'/albums', '/albums', Record<never, never>, Record<never, never>>,
    '/albums-artist': RouteRecordInfo<'/albums-artist', '/albums-artist', Record<never, never>, Record<never, never>>,
    '/artists': RouteRecordInfo<'/artists', '/artists', Record<never, never>, Record<never, never>>,
    '/music-favorites': RouteRecordInfo<'/music-favorites', '/music-favorites', Record<never, never>, Record<never, never>>,
    '/player': RouteRecordInfo<'/player', '/player', Record<never, never>, Record<never, never>>,
    '/playlists-favorites': RouteRecordInfo<'/playlists-favorites', '/playlists-favorites', Record<never, never>, Record<never, never>>,
  }
}
